### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by xianhuawei** [unknown-marketwizards/tradingview-desktop#2]
同样的账号密码，用chrome可以登录,用你这个提示   You have been locked out for too many login

**Comment by themarketwizard** [comment]
README.md 上写了
---
解决登陆失败问题
如果登陆时遇到下面错误

You have been locked out due to too many login attempts. Please try again later.

可以通过下面步骤解决：

点击左上角菜单
选择 Home
选择 ZH 简体中文
重新登陆
